name: VirusHD-Core
author: VirusHD
main: net.virushd.core.main.CoreMain
version: 1.0
loadbefore: [VirusHD-Coins, VirusHD-Pets, VirusHD-Troll, VirusHD-CityBuild, VirusHD-Creative, VirusHD-TTT]
depend: [VirusHD-Title, InventoryAPI]
commands:
  lobby:
    description: Lobby command
  admin:
    description: Admin command